### ISSUE TITLE
big-bang doesn't clear up canvas on each tick

### ISSUE THREAD

**Issue by vishesh** [soegaard/whalesong#12]
For example mouse.rkt in examples. Rendering in each each tick is done over previous tick canvas. Any ideas @schanzer?

**Comment by vishesh** [comment]
I've created a small patch which clears up canvas. Let me know if its a right approach

https://github.com/vishesh/whalesong/commit/08cab14e9d61f4f6e840e2253dc434486c59fee4

**Comment by schanzer** [comment]
Yes -  this is definitely correct
