### ISSUE TITLE
Compile as standalone xhtml broken

### ISSUE THREAD

**Issue by vishesh** [soegaard/whalesong#17]
Currently complains about contract violation in build-path used here[1]. Fixing that finishes the compile process, however the generated output doesn't run throwing up following error on JS console.

    Uncaught SyntaxError: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.

[1] https://github.com/vishesh/whalesong/blob/master/whalesong/whalesong-helpers.rkt#L133

**Comment by soegaard** [comment]
What was the error message build-path gave?

**Comment by vishesh** [comment]
Following is the original error. (current-output-port) is being passed instead of (current-output-dir). Replacing that fixes compile error, however output doesn't work as I said earlier.

build-path: contract violation
  expected: (or/c path-for-some-system? path-string? 'up 'same)
  given: #<output-port:stdout>
  argument position: 1st
  other arguments...:
   #<path:mouse.xhtml>
  context...:
   /home/vishesh/racket/whalesong/whalesong/whalesong-helpers.rkt:99:3
   /home/vishesh/racket/whalesong/whalesong/whalesong-cmd.rkt: [running body]
   /home/vishesh/racket/whalesong/whalesong/whalesong.rkt: [running body]

**Comment by vishesh** [comment]
I think I figured out what's wrong. I did following to make it work -
1. Firstly CDATA tags should be commented.
2. If we use a non-xhtml doctype like in regular builds, we don't face this error. It seems to be a jQuery specific bug with XHTML
