### ISSUE TITLE
`rotate` doesn't allow negative angles

### ISSUE THREAD

**Issue by stchang** [soegaard/whalesong#21]
`rotate` from whalesong/image is currently incompatible with `rotate` from 2htdp/image. It should accept any real number: http://docs.racket-lang.org/teachpack/2htdpimage.html?q=rotate#%28def._%28%28lib._2htdp%2Fimage..rkt%29._angle~3f%29%29

**Comment by soegaard** [comment]
If I recall correctly `rotate` in `2htdp/image` didn't rotate originally. The fix might be as simple as look up what the new rotate code looks like.

**Comment by soegaard** [comment]
If I recall correctly `rotate` in `2htdp/image` didn't rotate originally. The fix might be as simple as look up what the new rotate code looks like.

**Comment by soegaard** [comment]
If I recall correctly `rotate` in `2htdp/image` didn't rotate originally. The fix might be as simple as look up what the new rotate code looks like.

**Comment by soegaard** [comment]
If I recall correctly `rotate` in `2htdp/image` didn't rotate originally. The fix might be as simple as look up what the new rotate code looks like.

**Comment by soegaard** [comment]
If I recall correctly `rotate` in `2htdp/image` didn't rotate originally. The fix might be as simple as look up what the new rotate code looks like.

**Comment by soegaard** [comment]
If I recall correctly `rotate` in `2htdp/image` didn't rotate originally. The fix might be as simple as look up what the new rotate code looks like.

**Comment by soegaard** [comment]
If I recall correctly `rotate` in `2htdp/image` didn't rotate originally. The fix might be as simple as look up what the new rotate code looks like.

**Comment by soegaard** [comment]
See https://github.com/racket/htdp/commit/76aeee68d2bbbda14f559a9ba0f846d59bcb14df
