### ISSUE TITLE
implement stop-with

### ISSUE THREAD

**Issue by stchang** [soegaard/whalesong#23]
In particular, Realm of Racket examples need this construct.

**Comment by vishesh** [comment]
It was error at my end. I introduced this bug while introducing last-picture. Pushed a fix.

**Comment by stchang** [comment]
I believe we're talking about different things. I was referring to `stop-with`, which I don't think whalesong currently supports. I think you're referring to `stop-when`, is that right?

**Comment by vishesh** [comment]
Oh yes my bad.

**Comment by vishesh** [comment]
Created a pull request https://github.com/soegaard/whalesong/pull/30 @stchang  @schanzer
