### ISSUE TITLE
FYI raco setup errors reported

### ISSUE THREAD

**Issue by andrenventer** [soegaard/whalesong#45]
raco setup errors reported

raco setup: package declares no dependencies: "whalesong"
raco setup: --- summary of errors ---
raco setup: error: during making for <planet>/dyoo/whalesong.plt/1/21 (Whalesong)
raco setup:   ...nomad/Library/Racket/planet/300/6.2.1/cache/dyoo/whalesong.plt/1/21/parser/parse-bytecode-5.3.rkt:372:20: match: wrong number for fields for structure mod: expected 16 but got 15
raco setup:     at: (name srcname self-modidx prefix provides requires body syntax-body unexported max-let-depth dummy lang-info internal-context pre-submodules post-submodules)
raco setup:     in: (struct mod (name srcname self-modidx prefix provides requires body syntax-body unexported max-let-depth dummy lang-info internal-context pre-submodules post-submodules))
raco setup:     compiling: <planet>/dyoo/whalesong.plt/1/21/parser/parse-bytecode-5.3.rkt
raco setup: error: during making for <planet>/dyoo/whalesong.plt/1/21/compiler
raco setup:   ...nomad/Library/Racket/planet/300/6.2.1/cache/dyoo/whalesong.plt/1/21/parser/parse-bytecode-5.3.rkt:372:20: match: wrong number for fields for structure mod: expected 16 but got 15
raco setup:     at: (name srcname self-modidx prefix provides requires body syntax-body unexported max-let-depth dummy lang-info internal-context pre-submodules post-submodules)
raco setup:     in: (struct mod (name srcname self-modidx prefix provides requires body syntax-body unexported max-let-depth dummy lang-info internal-context pre-submodules post-submodules))
raco setup:     compiling: <planet>/dyoo/whalesong.plt/1/21/parser/parse-bytecode-5.3.rkt
raco setup: error: during making for <planet>/dyoo/whalesong.plt/1/21/js-assembler
raco setup:   ...nomad/Library/Racket/planet/300/6.2.1/cache/dyoo/whalesong.plt/1/21/parser/parse-bytecode-5.3.rkt:372:20: match: wrong number for fields for structure mod: expected 16 but got 15
raco setup:     at: (name srcname self-modidx prefix provides requires body syntax-body unexported max-let-depth dummy lang-info internal-context pre-submodules post-submodules)
raco setup:     in: (struct mod (name srcname self-modidx prefix provides requires body syntax-body unexported max-let-depth dummy lang-info internal-context pre-submodules post-submodules))
raco setup:     compiling: <planet>/dyoo/whalesong.plt/1/21/parser/parse-bytecode-5.3.rkt
raco setup: error: during making for <planet>/dyoo/whalesong.plt/1/21/make
raco setup:   ...nomad/Library/Racket/planet/300/6.2.1/cache/dyoo/whalesong.plt/1/21/parser/parse-bytecode-5.3.rkt:372:20: match: wrong number for fields for structure mod: expected 16 but got 15
raco setup:     at: (name srcname self-modidx prefix provides requires body syntax-body unexported max-let-depth dummy lang-info internal-context pre-submodules post-submodules)
raco setup:     in: (struct mod (name srcname self-modidx prefix provides requires body syntax-body unexported max-let-depth dummy lang-info internal-context pre-submodules post-submodules))
raco setup:     compiling: <planet>/dyoo/whalesong.plt/1/21/parser/parse-bytecode-5.3.rkt
raco setup: error: during making for <planet>/dyoo/whalesong.plt/1/21/parser
raco setup:   ...nomad/Library/Racket/planet/300/6.2.1/cache/dyoo/whalesong.plt/1/21/parser/parse-bytecode-5.3.rkt:372:20: match: wrong number for fields for structure mod: expected 16 but got 15
raco setup:     at: (name srcname self-modidx prefix provides requires body syntax-body unexported max-let-depth dummy lang-info internal-context pre-submodules post-submodules)
raco setup:     in: (struct mod (name srcname self-modidx prefix provides requires body syntax-body unexported max-let-depth dummy lang-info internal-context pre-submodules post-submodules))
raco setup:     compiling: <planet>/dyoo/whalesong.plt/1/21/parser/parse-bytecode-5.3.rkt

**Comment by andrenventer** [comment]
cleaned out the cache and tried again - this time it worked

**Comment by soegaard** [comment]
Hi Andre,

Nice to know you got it installed. I don't know why the install failed the
first time.

/Jens Axle
