### ISSUE TITLE
Inconsistency between README and ticket about version support

### ISSUE THREAD

**Issue by ylluminarious** [soegaard/whalesong#49]
In [this ticket](https://github.com/soegaard/whalesong/issues/48), @soegaard said that "... we are stuck with Racket 6.2." And the ticket itself is named "Compiling failed in Racket 6.3". However, the README file of this project says: "Whalesong needs Racket 5.2. As is Whalesong doesn't work on version 5.3 or greater." It appears that there is an inconsistency here in the specification of which versions are not supported. I'm not sure whether this was a simple mistake or if I'm missing something here.

**Comment by soegaard** [comment]
You are right! It should have ben 6.2 and 6.3 in the Readme.

**Comment by soegaard** [comment]
Please test with 6.2 and let me know if there are any problems.

**Comment by ylluminarious** [comment]
@soegaard Ok, thanks for the clarification, I'll definitely try it out at some point. I've had a lot of good experience with the [Opal project](https://github.com/opal/opal) and I'm excited to play with what appears to be its Racket counterpart :)
