### ISSUE TITLE
.racket/6.8/pkgs/whalesong/whalesong/lang/private/qq-and-or.rkt:108:118: idl: unbound identifier in module (in phase 1, transformer environment) in: idl

### ISSUE THREAD

**Issue by zaoqi** [soegaard/whalesong#51]
`.racket/6.8/pkgs/whalesong/whalesong/lang/private/qq-and-or.rkt:108:118: idl: unbound identifier in module (in phase 1, transformer environment) in: idl`

**Comment by soegaard** [comment]
Whalesong needs the old Racket version 6.2.
More information: https://github.com/soegaard/whalesong/issues/48

/Jens Axel
