### ISSUE TITLE
Compiling whalesong

### ISSUE THREAD

**Issue by AlbertoPL** [soegaard/whalesong#9]
Hello, I'm having an issue with compiling Whalesong. Let me start by saying that I tried to install the dyoo/whalesong version from the planet repository but to no avail. I actually end up getting the same error either way.

My problem right now is that when I run sudo make, I get this output:

raco planet link dyoo whalesong.plt 1 19 .
racket make-launcher.rkt
copy-file: cannot open source file
  source path: /home/alberto/racket/collects/launcher/sh
  destination path: /home/alberto/whalesong-master/whalesong/whalesong
  system error: No such file or directory; errno=2
make: *** [launcher] Error 1

Neither the source nor destination exists. In fact, I'm not sure why the destination is as such, since that's too many levels deep (the make file is in /home/alberto/whalesong-master/whalesong).

I appreciate any help you can provide.

**Comment by soegaard** [comment]
Hi Alberto,

You need to use my version of Whalesong to get it to compile in a new Racket.

In a terminal:
    git git@github.com:soegaard/whalesong.git
    raco make -j 1 whalesong

Also: Make sure to use the newest version of racket available from download.racket-lang.org

**Comment by AlbertoPL** [comment]
Hi Jens,

Thanks for the reply. I tried what you wrote but I think I'm having some
issues with it as neither command works for me.

I first get: git: 'git@github.com:soegaard/whalesong.git' is not a git
command. See 'git --help'.

So I tried git cloning instead. That downloads the repository but then the
second command does not work when I go into the whalesong directory. I get
this issue:

alberto@ubuntu:~/whalesong/whalesong$ raco make -j 1 whalesong
raco make: file does not exist: whalesong

I'm looking in the repository and I do not see a whalesong file. I do see
whalesong.rkt, but doing raco make -j 1 whalesong.rkt doesn't seem to do
anything.

Is there some configuration I need to do to make any of these steps work?

Thanks once again,

Alberto

**Comment by dkvasnicka** [comment]
You can install the package by issuing ```raco pkg install -j 1``` in the root of this project. But that won't install the launcher you need to compile stuff. And ```(require whalesong/make-launcher)``` fails:

```
-> % racket
Welcome to Racket v6.1.1.
> (require whalesong/make-launcher)
copy-file: cannot open source file
  source path: /opt/homebrew-cask/Caskroom/racket/6.1.1/Racket v6.1.1/collects/launcher/sh
  destination path: /Users/dkvasnicka/Desktop/whalesong/whalesong
  system error: No such file or directory; errno=2
  context...:
   /Users/dkvasnicka/Desktop/whalesong/whalesong/make-launcher.rkt:456:0: make-macosx-launcher
   /Users/dkvasnicka/Desktop/whalesong/whalesong/make-launcher.rkt: [running body]
   /opt/homebrew-cask/Caskroom/racket/6.1.1/Racket v6.1.1/collects/racket/private/misc.rkt:87:7
```

@soegaard Could you please update the README with build instructions? Thanks!

**Comment by soegaard** [comment]
Hi All,

Whalesong is now available through pkg.racket-lang.org. That means:

    raco pkg install -j 1 --force --deps search-auto --scope installation whalesong

will install Whalesong. Note that the -j 1 is needed in order to avoid build errors.
This also means that the package manager in DrRacket can not install Whalesong (yet).

**Comment by AlbertoPL** [comment]
Hello Jens,

This is working great, thank you! One thing I did so that I could access
Whalesong from any directory was to add the installation directory to my
path.

Thanks for all of your hard work, I'm loving this project so far!

-Alberto

On Sun, Mar 15, 2015 at 2:57 AM, Jens Axel Søgaard <notifications@github.com

**Comment by soegaard** [comment]
Great to hear it worked.
